export const DRIZZLE_CLIENT = Symbol('DRIZZLE_CLIENT');

export const ORGANIZATION_SEED_REPOSITORY = Symbol(
  'ORGANIZATION_SEED_REPOSITORY',
);
export const WALLET_REPOSITORY = Symbol('WALLET_REPOSITORY');
export const SIGNING_REQUEST_REPOSITORY = Symbol('SIGNING_REQUEST_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');

export const WALLET_NONCE_REPOSITORY = Symbol('WALLET_NONCE_REPOSITORY');
